project:
  type: website

website:
  site-url: https://flairmi.com
  title: "Flair Marketing Intelligence (FlairMI)"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Survey
        href: survey/index.qmd
      - text: Stats
        href: stats/index.qmd
      - text: Writer
        href: writer/index.qmd
      - text: Blog
        href: blog/index.qmd
      - text: About
        href: about.qmd
    right:
      - text: Starter Pack
        href: shop/index.qmd
      - text: Downloads
        href: downloads/index.qmd
  page-footer:
    left: |
      <a href="/downloads/PrivacyPolicy.md">Privacy</a> ·
      <a href="/downloads/TermsOfUse.md">Terms</a> ·
      <a href="/downloads/Refund_Cancellation_Policy.md">Refunds</a> ·
      <a href="/downloads/Affiliate_Sponsorship_Disclosure.md">Disclosure</a>
    right: |
      <a href="mailto:contact@flairmi.com?subject=FlairMI%20Feedback">Feedback</a>

# Global author metadata (proper given/family names to fix citations)
author:
  - family: Sharafuddin
    given: Mohammed Ali
    name: Mohammed Ali Sharafuddin
    url: https://flairmi.com/about/
    affiliation: FlairMI
    affiliation-url: https://flairmi.com
    orcid: 0000-0001-5247-2964

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    include-in-header: [assets/seo/site_schema.html]
    code-fold: true
    mathjax: true

# Analytics placeholder
# Uncomment and add your analytics service ID when ready
# Options: Google Analytics, Plausible, etc.
# analytics:
#   google-analytics: "G-XXXXXXXXXX"
#   # or for Plausible:
#   # plausible:
#   #   domain: flairmi.com
#
# Goal events to track:
#   - download_starter_pack: User downloads FlairMI Starter Pack
#   - checkout_click: User clicks "Proceed" on shop/index
#   - sponsor_kit_open: User opens FlairMI_Sponsor_Kit.md
#   - calendar_view: User views Availability_Calendar.md
#   - mock_purchase: Shop checkout completion (logged to console)

metadata:
  open-graph: true
  twitter-card: true
  bibliography: assets/refs/references.bib

sitemap: true